# Generated by Django 4.2.1 on 2023-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_review_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
